model_params:
    model_name: GCVAE   # Choose between [GVAE, GCVAE]
    h_dim:  512         # Hidden dimensions
    z_dim:  110          # Latent dimensions
    n:  1               # Triples per graph
    beta:   0.6         # betaVAE ratio
    epochs: 111
    lr: 0.00001
    batch_size_exp2: 13 # 2**(batch_size_exp)

dataset_params:
    dataset_name: fb15k

experiment:
    exp_name: tune_GCVAElr5
    train:  true
    link_prediction:    true
    load_model: false
    load_model_path:    []
