wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    code_path: code/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
dataset_params:
  desc: null
  value:
    dataset_name: fb15k
experiment:
  desc: null
  value:
    exp_name: test_config
    link_prediction: true
    load_model: false
    load_model_path: /home/wolf/Thesis/Code/rgvae/results/exp_20201119/GCVAE_fb15k_20201119.pt
    train: true
model_params:
  desc: null
  value:
    batch_size_exp2: 3
    beta: 0.6
    epochs: 11
    h_dim: 512
    lr: 1.0e-06
    model_name: GCVAE
    n: 1
    z_dim: 60
