model_params:
    model_name: GCVAE2   # Choose between [GVAE, GCVAE, GCVAE2]
    h_dim:  512         # Hidden dimensions
    z_dim:  60          # Latent dimensions
    n:  1               # Triples per graph
    beta:   0.6         # betaVAE ratio
    epochs: 11
    lr: 0.000001
    batch_size_exp2: 3 # 2**(batch_size_exp)

dataset_params:
    dataset_name: fb15k

experiment:
    exp_name: test_config_GCVAE2
    train:  true
    link_prediction:    true
    load_model: false
    load_model_path:    /home/wolf/Thesis/Code/rgvae/results/exp_20201119/GCVAE_fb15k_20201119.pt
