batch_size_exp2: 6
beta: 1
dataset_name: fb15k
epochs: 1
exp_name: config_file
h_dim: 512
k: 9
link_prediction: false
load_model: false
load_model_path: []
lr: 5.0e-05
model_name: GCVAE
n: 1
train: true
z_dim: 100
perm_inv: true
final: true
eval_generation: false
delta: 0.6