batch_size_exp2: 6
beta: 100
dataset_name: wn18rr
epochs: 200
exp_name: config_file
h_dim: 512
k: 9
link_prediction: false
load_model: false
load_model_path: []
lr: 5.0e-05
model_name: GCVAE2
n: 1
train: true
z_dim: 100
